[features]
seeds = false
skip-lint = false

[programs.localnet]
workspace = "GJpDE682RqjTKT75Hjii3KqUaW5ddhwqLWy1afH4XR5u"

[programs.devnet]
workspace = "GJpDE682RqjTKT75Hjii3KqUaW5ddhwqLWy1afH4XR5u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:\\Users\\lcifuentes\\.config\\solana\\id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
